### PR TITLE
Add build status to README

### PR DESCRIPTION
**Pull request by egh**
Testing a TC build status icon in the README.

See https://github.com/PLOS/content-repo/blob/98cd3baf3db0d689720f9b814241ce43365ddccd/README.md

### CODE REVIEW

**Comment by slimeate** [comment]
Looks good! But waddaya think about also adding a badge for the integration tests as well? https://teamcity.plos.org/teamcity/viewType.html?buildTypeId=IntegrationTests_CRepoDev

**Comment by egh** [comment]
Good idea. I tried to make it look as nice as I could: https://github.com/PLOS/content-repo/blob/6711e03e1dbbed75f57d0c8eebf49ecb9b52cf76/README.md

**Comment by slimeate** [comment]
COol! Sorry, I should have thought to ask this before, but what branch is this reporting on? It doesn't look like one is specified, so is it reporting on the default branch (sounds good), or just whatever branch happened to build most recently (sounds not-so-good).

**Comment by egh** [comment]
image
wtf

**Comment by egh** [comment]
Testing with https://github.com/PLOS/content-repo/pull/135

**Comment by egh** [comment]
It seems to work as expected: the latest build is a failure (https://teamcity.plos.org/teamcity/viewType.html?buildTypeId=CRepo_Build&tab=buildTypeHistoryList) but the status icon is green https://github.com/PLOS/content-repo/blob/6711e03e1dbbed75f57d0c8eebf49ecb9b52cf76/README.md

**Comment by egh** [comment]
final version with SVG icons https://github.com/PLOS/content-repo/blob/bfff62806e10516026953c618a4dca1a839ec031/README.md

**Comment by slimeate** [comment]
Ok, cool, I'm convinced. Thanks for double checking!

**Pull request merged**
